import React, { useEffect, useState } from "react";
import { useChat } from "../hooks/useChat";

export const PoseDebugger = () => {
  const { role, yogaPose, setYogaPose } = useChat();
  const [poses, setPoses] = useState([]);

  // Load available poses from the JSON file generated by MediaPipe
  useEffect(() => {
    fetch("/src/poses.json")
      .then((res) => res.json())
      .then((data) => {
        setPoses(Object.keys(data));
      })
      .catch((err) => console.error("Failed to load poses.json:", err));
  }, []);

  if (role !== "Yoga" && role !== "Kickboxing") return null;

  return (
    <div className="fixed top-24 left-4 z-50 glass-card p-4 rounded-xl shadow-lg w-64 max-h-[70vh] flex flex-col pointer-events-auto overflow-hidden">
      <div className="flex items-center gap-2 mb-3 px-1 border-b border-sage-200 pb-2">
        <span className="text-lg">🧘</span>
        <h3 className="font-bold text-warm-800 text-sm">3D Pose Debugger</h3>
      </div>
      
      <p className="text-xs text-warm-500 mb-3 px-1 font-medium">
        Procedurally generated from images via MediaPipe + Kalidokit IK
      </p>

      <div className="flex-1 overflow-y-auto pr-1 space-y-2 custom-scrollbar">
        <button
          onClick={() => setYogaPose(null)}
          className={`w-full text-left px-3 py-2 rounded-lg text-sm transition-all border ${
            yogaPose === null
              ? "bg-sage-500 text-white border-sage-600 shadow-sm"
              : "bg-white/50 text-warm-700 border-sage-200 hover:bg-sage-50 hover:border-sage-400"
          }`}
        >
          Reset / Default Animation
        </button>

        {poses.map((poseName) => (
          <button
            key={poseName}
            onClick={() => setYogaPose(poseName)}
            className={`w-full text-left px-3 py-2 rounded-lg text-sm transition-all border capitalize ${
              yogaPose === poseName
                ? "bg-coral-500 text-white border-coral-600 shadow-sm"
                : "bg-white/50 text-warm-700 border-sage-200 hover:bg-sage-50 hover:border-sage-400"
            }`}
          >
            {poseName.replace(/_/g, " ")}
          </button>
        ))}
        
        {poses.length === 0 && (
          <div className="text-xs text-center text-warm-400 py-4 animate-pulse">
            Loading poses...
          </div>
        )}
      </div>
    </div>
  );
};
